using System.ComponentModel;
using WinRTWriterLib.Templates;

namespace WinRTWriterLib
{
    namespace Templates
    {
        internal interface Transformer
        {
            public string TransformText();
        }
        public partial class NamespaceTemplate : Transformer
        {
            public NamespaceTemplate(WinRTNamespace @namespace, IDLWriter writer)
            {
                Namespace = @namespace;
                Writer = writer;
            }
            public IDLWriter Writer { get; }

            public WinRTNamespace Namespace { get; }
        }

        public partial class RuntimeClassTemplate : Transformer
        {
            public RuntimeClassTemplate(WinRTRuntimeClass @class, IDLWriter writer)
            {
                Class = @class;
                Writer = writer;
            }
            public IDLWriter Writer { get; }
            public WinRTRuntimeClass Class { get; }
        }

        public partial class InterfaceTemplate : Transformer
        {
            public InterfaceTemplate(WinRTInterface @interface, IDLWriter writer)
            {
                Interface = @interface;
                Writer = writer;
            }
            public IDLWriter Writer { get; }
            public WinRTInterface Interface { get; }
        }

        public partial class PropertyTemplate : Transformer
        {
            public PropertyTemplate(WinRTProperty property, IDLWriter writer)
            {
                Property = property;
                Writer = writer;
            }
            public IDLWriter Writer { get; }
            public WinRTProperty Property { get; }
        }

        public partial class MethodTemplate : Transformer
        {
            public MethodTemplate(WinRTMethod method, IDLWriter writer)
            {
                Method = method;
                Writer = writer;
            }
            public IDLWriter Writer { get; }
            public WinRTMethod Method { get; }
        }

        public partial class AttributeUsageTemplate : Transformer
        {
            public AttributeUsageTemplate(WinRTAttributeUsage attribute, IDLWriter writer)
            {
                Attribute = attribute;
                Writer = writer;
            }
            public IDLWriter Writer { get; }
            public WinRTAttributeUsage Attribute { get; }
        }

        public partial class EnumTemplate : Transformer
        {
            public EnumTemplate(WinRTEnum @enum, IDLWriter writer)
            {
                Enum = @enum;
                Writer = writer;
            }
            public IDLWriter Writer { get; }
            public WinRTEnum Enum { get; }
        }
    }

    public class IDLWriter : IWriter
    {
        public void Write(IEnumerable<WinRTNamespace> namespaces)
        {
            Console.WriteLine("// This file was generated by a tool");
            foreach (var ns in namespaces.Select(_ => _.GetTopLevel()).Distinct())
            {
                var output = Transform(ns);
                Console.WriteLine(output);
            }
        }



        internal int Indent { get; set; }
        internal string Transform(WinRTEntity entity, bool withIndent = true)
        {
            Transformer? transformer = GetTransformer(entity);
            var output = transformer?.TransformText() ?? string.Empty;
            if (!withIndent) return output;
            var indented = output.Split(Environment.NewLine);
            var res = string.Join(Environment.NewLine, indented.Select(x => string.IsNullOrWhiteSpace(x) ? x : (Indent == 0 ? x : new string(' ', 4) + x)));
            return res;

        }

        internal string Transform(List<WinRTAttributeUsage> attrs, bool withNewlines)
        {
            if (withNewlines)
            {
                var t = attrs.Select(_ => Transform(_, false));
                return string.Join(Environment.NewLine, t);
            }
            else
            {
                var oldIndent = Indent;
                Indent = 0;
                var ret = string.Concat(attrs.Select(_ => Transform(_, true)));
                Indent = oldIndent;
                return ret;
            }
        }
        private Transformer? GetTransformer(WinRTEntity entity)
        {
            Transformer? transformer = null;
            var transformerName = $"WinRTWriterLib.Templates.{entity.GetType().Name.Replace("WinRT", "")}Template";
            try
            {
                var type = Type.GetType(transformerName);
                var ctor = type!.GetConstructor(new Type[] { entity.GetType(), this.GetType() });
                transformer = ctor!.Invoke(new object[] { entity, this }) as Transformer;
                return transformer;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            return transformer;
        }

        public void EnterScope()
        {
            Indent++;
        }

        public void ExitScope()
        {
            Indent--;
        }
    }
}